module.exports = [
    {"label": "Anthropological Linguistics", "data": "anthropological_linguistics"},
    {"label": "Applied Linguistics", "data": "applied_linguistics"},
    {"label": "Cognitive Science", "data": "cognitive_science"},
    {"label": "Computational Linguistics", "data": "computational_linguistics"},
    {"label": "Discourse Analysis", "data": "discourse_analysis"},
    {"label": "Forensic Linguistics", "data": "forensic_linguistics"},
    {"label": "General Linguistics", "data": "general_linguistics"},
    {"label": "Historical Linguistics", "data": "historical_linguistics"},
    {"label": "History of Linguistics", "data": "history_of_linguistics"},
    {"label": "Language Acquisition", "data": "language_acquisition"},
    {"label": "Language Documentation", "data": "language_documentation"},
    {"label": "Lexicography", "data": "lexicography"},
    {"label": "Linguistics and Literature", "data": "linguistics_and_literature"},
    {"label": "Linguistic Theories", "data": "linguistic_theories"},
    {"label": "Mathematical Linguistics", "data": "mathematical_linguistics"},
    {"label": "Morphology", "data": "morphology"},
    {"label": "Neurolinguistics", "data": "neurolinguistics"},
    {"label": "Philosophy of Language", "data": "philosophy_of_language"},
    {"label": "Phonetics", "data": "phonetics"},
    {"label": "Phonology", "data": "phonology"},
    {"label": "Pragmatics", "data": "pragmatics"},
    {"label": "Psycholinguistics", "data": "psycholinguistics"},
    {"label": "Semantics", "data": "semantics"},
    {"label": "Sociolinguistics", "data": "sociolinguistics"},
    {"label": "Syntax", "data": "syntax"},
    {"label": "Text and Corpus Linguistics", "data": "text_and_corpus_linguistics"},
    {"label": "Translating and Interpreting", "data": "translating_and_interpreting"},
    {"label": "Typology", "data": "typology"},
    {"label": "Writing Systems", "data": "writing_systems"},
    {"label": "Other", "data": "Other"},
    {"label": "Unknown", "data": "Unknown"}
]
