module.exports = {
  /* AUTH ACTIONS */
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  CHECK_AUTH_STATE: "CHECK_AUTH_STATE",

  /* MESSAGE ACTIONS */
  DISMISS_MESSAGE: "DISMISS_MESSAGE",

  /* BROWSER ACTIONS */

  /* loading of items (may fail or succeed) */
  LOAD_ITEMS: "LOAD_ITEMS",
  LOAD_ITEMS_SUCCESS: "LOAD_ITEMS_SUCCESS",
  LOAD_ITEMS_FAILURE: "LOAD_ITEMS_FAILURE",

  /* loading of spec */
  LOAD_COMPONENT_SPEC: "LOAD_COMPONENT_SPEC",
  LOAD_COMPONENT_SPEC_SUCCES: "LOAD_COMPONENT_SPEC_SUCCES",
  LOAD_COMPONENT_SPEC_XML_SUCCES: "LOAD_COMPONENT_SPEC_XML_SUCCES",
  LOAD_COMPONENT_SPEC_FAILURE: "LOAD_COMPONENT_SPEC_SUCCES_FAILURE",

  /* loading of one item */
  LOAD_ITEM_SUCCESS: "LOAD_ITEM_SUCCESS",
  LOAD_ITEM_FAILURE: "LOAD_ITEM_FAILURE",

  /* delete components */
  DELETE_COMPONENTS: "DELETE_COMPONENTS",
  DELETE_COMPONENTS_SUCCESS: "DELETE_COMPONENTS_SUCCESS",
  DELETE_COMPONENTS_FAILURE: "DELETE_COMPONENTS_FAILURE",
  DELETE_STATE_DELETED: "DELETE_STATE_DELETED",
  DELETE_STATE_DELETING: "DELETE_STATE_DELETING",

  /* loading of comments */
  LOAD_COMMENTS: "LOAD_COMMENTS",
  LOAD_COMMENTS_SUCCESS: "LOAD_COMMENTS_SUCCESS",
  LOAD_COMMENTS_FAILURE: "LOAD_COMMENTS_FAILURE",

  /* saving comments */
  SAVE_COMMENT: "SAVE_COMMENT",
  SAVE_COMMENT_SUCCESS: "SAVE_COMMENT_SUCCESS",
  SAVE_COMMENT_FAILURE: "SAVE_COMMENT_FAILURE",

  /* deleting comments */
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAILURE: "DELETE_COMMENT_FAILURE",

  /* save spec */
  SAVE_COMPONENT_SPEC: "SAVE_COMPONENT_SPEC",
  SAVE_COMPONENT_SPEC_SUCCESS: "SAVE_COMPONENT_SPEC_SUCCESS",
  SAVE_COMPONENT_SPEC_FAILURE: "SAVE_COMPONENT_SPEC_FAILURE",

  /* grid filter text changes */
  FILTER_TEXT_CHANGE: "FILTER_TEXT_CHANGE",

  /* component view */
  TOGGLE_ITEM_EXPANSION: "TOGGLE_ITEM_EXPANSION",
  LINKED_COMPONENTS_LOADED: "LINKED_COMPONENTS_LOADED",

  /* toggle item selection in the browser */
  SELECT_BROWSER_ITEM: "SELECT_BROWSER_ITEM",
  /* toggle selection mode */
  SWITCH_MULTIPLE_SELECT: "SWITCH_MULTIPLE_SELECT",
  /* switch space (registry (private, public, group...) and type (components/profiles)) */
  SWITCH_SPACE: "SWITCH_SPACE",

  /* start editing an item */
  EDIT_ITEM: "EDIT_ITEM",
  /* open editor with item */
  OPEN_EDITOR: "OPEN_EDITOR",

  LOAD_EDITOR_ITEMS: "LOAD_EDITOR_ITEMS",
  LOAD_EDITOR_ITEMS_SUCCESS: "LOAD_EDITOR_ITEMS_SUCCESS",
  LOAD_EDITOR_ITEMS_FAILURE: "LOAD_EDITOR_ITEMS_FAILURE",

  SELECT_EDITOR_GRID_ITEM: "SELECT_EDITOR_GRID_ITEM",
  SWITCH_EDITOR_GRID_SPACE: "SWITCH_EDITOR_GRID_SPACE",

  TOGGLE_COMPONENT_SELECTION: "TOGGLE_COMPONENT_SELECTION",

  /* spec updated for editor */
  COMPONENT_SPEC_UPDATED: "COMPONENT_SPEC_UPDATED",
  /* item description updated for editor */
  ITEM_UPDATED: "ITEM_UPDATED",

  /* ITEM TYPES */
  TYPE_PROFILE: "profiles",
  TYPE_COMPONENTS: "components",

  /* ITEM SPACES */
  SPACE_PUBLISHED: "SPACE_PUBLISHED",
  SPACE_PRIVATE: "SPACE_PRIVATE",
  SPACE_GROUP: "SPACE_GROUP",

  /* INFO VIEWS */
  INFO_VIEW_SPEC: "INFO_VIEW_SPEC",
  INFO_VIEW_XML: "INFO_VIEW_XML",
  INFO_VIEW_COMMENTS: "INFO_VIEW_COMMENTS"
};
