module.exports = {
  /* BROWSER ACTIONS */

  /* loading of items (may fail or succeed) */
  LOAD_ITEMS: "LOAD_ITEMS",
  LOAD_ITEMS_SUCCESS: "LOAD_ITEMS_SUCCESS",
  LOAD_ITEMS_FAILURE: "LOAD_ITEMS_FAILURE",

  /* loading of spec */
  LOAD_COMPONENT_SPEC: "LOAD_COMPONENT_SPEC",
  LOAD_COMPONENT_SPEC_SUCCES: "LOAD_COMPONENT_SPEC_SUCCES",
  LOAD_COMPONENT_SPEC_SUCCES_FAILURE: "LOAD_COMPONENT_SPEC_SUCCES_FAILURE",

  /* loading of comments */
  LOAD_COMMENTS: "LOAD_COMMENTS",
  LOAD_COMMENTS_SUCCESS: "LOAD_COMMENTS_SUCCESS",
  LOAD_COMMENTS_FAILURE: "LOAD_COMMENTS_FAILURE",

  /* start editing an item */
  EDIT_ITEM: "EDIT_ITEM",
  /* toggle item selection in the browser */
  SELECT_BROWSER_ITEM: "SELECT_BROWSER_ITEM",
  /* toggle selection mode */
  SWITCH_MULTIPLE_SELECT: "SWITCH_MULTIPLE_SELECT",

  /* ITEM TYPES */
  TYPE_PROFILE: "profiles",
  TYPE_COMPONENTS: "components",

  /* ITEM SPACES */
  SPACE_PUBLISHED: "published",
  SPACE_PRIVATE: "private"
};
